// eslint-disable
export default {
    'domainname': {
        'CAT_SOLAR': 'Solar',
        'CAT_WIND': 'Wind',
        'CAT_EV_CHARGING': 'Charge Point',
        'AUTH_CAT_CONFIG': 'EOS',
        'CAT_STORAGE': 'Storage Station',
        'CAT_HOME': 'Home'
    },
    'category': {
        '21': 'Wind',
        '22': 'Solar',
        '23': 'Charging',
        '24': 'Portfolio',
        '25': 'Consumption',
        '26': 'Energy Storage',
        '27': 'Circle',
        '28': 'Sub-station',
        '40': 'EOS'
    },
    'errorCode': {
        '1000': 'Unknown Error',
        '1001': 'Service unavailable',
        '1002': 'Internal error',
        '1003': 'Database operation exception',
        '1004': 'Invalid Parameter',
        '1005': 'Invalid login',
        '2000': 'Edge does not exist',
        '2001': 'Edge has been bound',
        '2002': 'Edge cannot be bound to a different OU',
        '2003': 'Failed to change the edge name',
        '2004': 'Failed to register edge',
        '2005': 'Failed to update edge',
        '2006': 'The Edge does not exist',
        '2007': 'Failed to publish specific edge',
        '2008': 'Failed to delete edge because it has sub-devices',
        '2009': 'Failed to delete edge because it does not belong to this OU',
        '2010': 'Failed to delete edge',
        // eslint-disable-next-line max-len
        '2011': 'Create a public gateway model and gateway product under the OU first',
        '2012': 'Failed to insert edge',
        '2013': 'No system OU found. Check the Lion configuration',
        '2014': 'The box model as a gateway product is not a public model.',
        '2015': 'The box model as the gateway product should be named after standard model name: EnOS_Edge_Standard_Model',
        '2016': 'Cross-OU queries not allowed',
        '3000': 'Failed to upload file due to unsupported file type',
        '3001': 'Failed to upload file because the file is not encoded in UTF8 or BOM',
        '3002': 'Failed to upload file due to failure in reading file stream',
        '3003': 'Failed to upload file due to failure in saving file',
        '3004': 'Failed to upload file due to failure in deleting latest file',
        '3005': 'Failed to obtain file content',
        '3006': 'Failed to update file content',
        '3007': 'Failed to add file',
        '3008': 'Failed to delete file',
        '3009': 'Point.csv contain invalid content',
        '3010': 'Script does not exist',
        // eslint-disable-next-line max-len
        '3011': 'The function parameters used by the script contain a model feature identifier that does not exist',
        '3012': 'The script has a syntax error',
        '3013': 'The script does not contain a model feature identifier',
        '4000': 'Failed to add connection due to failure in obtaining the path of protocol.sys',
        '4001': 'Failed to add connection due to failure in copying standard protocol.sys',
        '4002': 'Failed to add connection due to failure in calling the service to add connection',
        '4003': 'The connection does not exist',
        '4004': 'Failed to delete connection because one or multiple sub-devices exist',
        '4005': 'Failed to delete connection',
        '4006': 'Failed to add device',
        '4007': 'Failed to update device because the device does not exist',
        '4008': 'Failed to update device because the edge ID of the device is inconsistent',
        '4009': 'Failed to update device because the connection ID of the device is inconsistent',
        '4010': 'Failed to update device because the asset ID of the specific device is inconsistent',
        '4011': 'Failed to update device',
        '4012': 'Failed to unbind device connection because the device does not exist',
        '4013': 'Failed to unbind device connection because the edge ID of the device is inconsistent',
        '4014': 'Failed to unbind device connection because the connection ID of the device is inconsistent',
        '4015': 'Failed to unbind device connection',
        // eslint-disable-next-line max-len
        '4016': 'Template of multi-channel-imported device is a duplicate of the template that the device has bound to',
        // eslint-disable-next-line max-len
        '4017': 'The model is not consistent for multi-channel-imported device',
        // eslint-disable-next-line max-len
        '4018': 'Mapping of the model point already exists in the template for multi-channel-imported device',
        // eslint-disable-next-line max-len
        '4019': 'Model point mapping already exists. Pass-through point mapping already exists',
        '4020': 'Connection does not exist when importing devices under the connection',
        '4021': 'Device does not exist when importing devices under the connection',
        '4022': 'Deivce template does not exist when importing devices under the connection',
        '4023': 'Protocol of the connection does not exist when importing devices under the connection',
        // eslint-disable-next-line max-len
        '4024': 'Protocol associated with the template is not of the same type as the protocol associated with the connection when importing devices under the connection',
        // eslint-disable-next-line max-len
        '4025': 'Device cannot be added again in non-multichannel mode when importing devices under the connection',
        // eslint-disable-next-line max-len
        '4026': 'Device is already added either by another Edge device or this connection when importing devices under the connection',
        '4027': 'Failed to update device when imporitng devices under the connection',
        '4028': 'Failed to import device when when imporitng devices under the connection',
        '4029': 'Logic address already exists',
        '4030': 'Logic address cannot be empty',
        '4031': 'Logic address cannot contain Chinese characters',
        '4032': 'More than the maximum number of single batch',
        // eslint-disable-next-line max-len
        '5000': 'The model ID in the mapping list is inconsistent with that in the template basic information',
        '5001': 'The template does not exist',
        '5002': 'Failed to add template',
        '5003': 'The template is already in use',
        '5004': 'Failed to obtain model by OU',
        '5005': 'Failed to obtain model information',
        '5006': 'Failed to obtain mapping information',
        '5007': 'Invalid format of point.csv',
        '5008': 'Failed to obtain content of point.csv',
        '5009': 'Failed to obtain calculating script',
        '5010': 'Failed to obtain basic information of the template',
        '5011': 'Failed to save mapping information to database',
        '5012': 'Failed to update template',
        '5013': 'Failed to delete point from database',
        '5014': 'Failed to insert point into database',
        '5015': 'Failed to update point',
        '5016': 'The file contains no valid data',
        '5017': 'Cannot find model',
        '5018': 'The template already exists',
        '5019': 'The device point is wrong',
        '5020': 'Invalid mapping list',
        '5021': 'Cannot obtain formula',
        '5022': 'The formula cannot be recognized',
        '5023': 'Failed to transfer mapping data',
        '5024': 'The mapping does not exist',
        '5025': 'Incorrect mapping of template',
        '5026': 'The format of the formula is invalid',
        '5027': 'Model point is already mapped',
        '5028': 'Cannot find device point',
        '5029': 'Protocol type cannot be changed when the template is in use',
        '5030': 'Some rows have wrong number of columns',
        '5031': 'The file contains duplicate point names or reference names',
        '5032': 'Failed to partially update the template',
        '5033': 'Failed to query template details',
        '6000': 'Failed to turn on debugging',
        '6001': 'Failed to turn off debugging',
        '6002': 'Failed to debug',
        '6003': 'Failed to set num',
        '6004': 'The debug command is not allowed',
        '6005': 'Invalid parameters in the debug command',
        '7000': 'Invalid protocol type',
        '7001': 'Repeat insert protocol group',
        '7002': 'Failed to insert protocol group',
        '7003': 'The inserted protocol is inconsistent with the associated protocol group',
        '7004': 'Cannot insert a release version of the protocol',
        '7005': 'Failed to insert protocol',
        '7006': 'The protocol or protocol group does not exist',
        '7007': 'Released protocol cannot be published or updated',
        '7008': 'Failed to publish protocol',
        '7009': 'Failed to delete protocol because the protocol has already been associated with a connection',
        '7010': 'Failed to delete protocol failed because another protocol is associated with it',
        '7011': 'Delete protocol failed',
        '7012': 'Delete protocol group failed',
        '7013': 'The newest version is debug',
        '7014': 'Failed to upgrade protocol',
        '7015': 'Failed to update protocol with the associate templates',
        '7016': 'Cannot find the associated protocol group',
        '7017': 'Failed to update protocol',
        '7018': 'Failed to update protocol group',
        '7019': 'Failed to update the associated connection when upgrading the protocol'
    },
    'common': {
        'add': 'Add',
        'cancel': 'Cancel',
        'confirm': 'Confirm',
        'tip': 'Tip',
        'edit': 'Edit',
        'save': 'Save',
        'upload': 'Upload',
        'download': 'Download',
        'replace': 'Replace',
        'true': 'True',
        'false': 'False',
        'update': 'Update',
        'upgrade': 'Upgrade',
        'delete': 'Delete',
        'batchDelete': 'Batch Delete',
        'submit': 'Submit',
        'import': 'Import',
        'export': 'Export',
        'back': 'Back',
        'release': 'Release',
        'create': 'Create',
        'view': 'View',
        'measurepoint': 'Measure Points',
        'service': 'Service',
        'event': 'Event',
        'attribute': 'Attributes',
        'bin': 'Bin file',
        'protocolDoc': 'Document',
        'close': 'Close',
        'ou': 'OU',
        'NO_ACCESS': 'No permission. Contact system administrator',
        'searchHint': 'Search by keyword',
        'noData': 'No Data'
    },
    'navheader': {
        'dateformat': '{0}-{1}-{2} {3}:{4}:{5} {6}',
        'dashboard': 'Dashboard',
        'stationdata': 'Assets',
        'stationconfig': 'Asset Management.',
        'stationorg': 'Asset Tree',
        'addstation': 'New Site',
        'stationdetail': 'Site Detail',
        'access': 'Connection',
        'addbox': 'Add Box',
        'devicelist': 'Device List',
        'modelconf': 'Model Configuration',
        'modellist': 'Model List',
        'modelimport': 'Model',
        'devicemodellist': 'Device Model List',
        'devicedetail': 'Device Detail',
        'newdriver': 'New Driver',
        'authconfig': 'Account',
        'authrole': 'Role Management',
        'authuser': 'User Management',
        'domaindetail': 'Domain Detail',
        'devicetype': 'Configuration',
        'accessop': 'Access Configuration',
        'adddevice': 'Add Device',
        'newchildmodule': 'New Child Model',
        'basicdomain': 'Basic Model',
        'partnerconfig': 'Partner Configuration',
        'customerconfig': 'Customer Configuration',
        'usercenter': 'User Center',
        'usergrouplist': 'User Group Management',
        'asscenter': 'Access Configuration',
        'tplmgt': 'Template Management',
        'alarmconfig': 'Event',
        'alarmrulepublib': 'Global Rules',
        'alarmset': 'Global Event Grouping',
        'alarmcontentpublib': 'Global Content Definition',
        'alarmcontentprivate': 'Content Definition',
        'alarmruleprivate': 'Rules',
        'alarmsetprivate': 'Event Group',
        'protocol': 'Protocol',
        'safeconf': 'Safety Configuration',
        'deviceaccess': 'Device Connection'
    },
    'nopermission': {
        'warn': 'The current user has no permission. Log in with another account.',
        'switch': 'Switch User'
    },
    'deviceaccess': {
        'connected': 'Connected',
        'disconnected': 'Disconnected',
        'publishing': 'Publishing',
        'publishSuccess': 'Published',
        'publishFail': 'Failed to publish',
        'unpublish': 'Unpublish',
        'deviceAccess': 'Edge Management',
        'searchHint': 'Search by keyword',
        'add': 'New Edge',
        'name': 'Name',
        'version': 'Version',
        'publishStatus': 'Publish State',
        'lastPublishTime': 'Last Published',
        'status': 'Status',
        'operation': 'Operations',
        'connectDevice': 'View',
        'addTitle': 'Add Edge',
        'nameSearchHint': 'Search by name',
        'productName': 'Product Name',
        'type': 'Type',
        'gateway': 'Edge Gateway',
        'extensive': 'Edge Platform',
        'logger': 'Edge Logger'
    },
    'boxconf': {
        'connected': 'Connected',
        'disconnected': 'Disconnected',
        'publishing': 'Publishing',
        'publishSuccess': 'Published',
        'publishFail': 'Failed to publish',
        'unpublish': 'To be published',
        'edgePublishSuccess': 'Edge published',
        'edgeDeleteSuccess': 'Edge deleted',
        'protocolEditSuccess': 'Content updated',
        'deleteEdge': 'Delete Edge',
        'downloadConfig': 'Download Configuration',
        'downloadResource': 'Download Resource',
        'collectDeleteTip': 'Are you sure you want to delete the connection?',
        'edgeDeleteTip': 'Are you sure you want to delete Edge gateway?',
        'deviceCount': 'Sub-devices',
        'address': 'Address',
        'protocolType': 'Protocol Type',
        'protocol': 'Protocol',
        'configFile': 'Configuration File',
        'addDevice': 'Add Device',
        'editDevice': 'Edit Devie',
        'test': 'Test',
        'primaryAddressRepeat': 'Primary address already exists',
        'secondaryAddressRepeat': 'Standby Address already exists',
        'basicInformation': 'Basic Information',
        'name': 'Name:',
        'edgeVersion': 'Edge Version:',
        'publishStatus': 'Publish State:',
        'lastPublishTime': 'Last Published:',
        'status': 'State:',
        'nonDirect': 'Connections',
        'deviceCountCon': 'Sub-devices:',
        'addCollect': 'Add Connection',
        'editCollect': 'Edit Connection',
        'publish': 'Publish',
        'connectDevice': 'Edge Detail',
        'tcpClient': 'TCP/IP Client',
        'tcpServer': 'TCP/IP Server',
        'httpsClient': 'HTTP(s) Client',
        'httpsServer': 'HTTP(s) Server',
        'other': 'Others',
        'primaryIpEmpty': 'Primary IP required',
        'portEmpty': 'Port required',
        'primaryAddressEmpty': 'Primary Address required',
        'ipFormat': 'Invalid IP address format',
        'portRange': 'Port should be an integer from 1 to 165535',
        'primarySecondaryRepeat': 'Primary Address and Standby Address cannot be identical',
        'wrongFormat': 'Invalid format',
        'collectName': 'Name',
        'collectNameEmpty': 'Connection name required',
        'mode': 'Mode',
        'modeEmpty': 'Mode required',
        'isShort': 'Is Short Connection',
        'primaryAddress': 'Primary Interface',
        'secondaryAddress': 'Standby Interface',
        'protocolTypeEmpty': 'Protocol type required',
        'protocolEmpty': 'Protocol required',
        'editCollectTip': 'The configuration file will be reset to default if the protocol is changed.',
        'logicAddressTip': 'Chinese not supported in logic address',
        'offsetFormat': 'Invalid offset value format',
        'offsetRange': 'Invalid range',
        'template': 'Template',
        'templateEmpty': 'Template required',
        'logicAddress': 'Logic Address',
        'logicAddressEmpty': 'Logic address required',
        'assetId': 'Asset ID',
        'aiOffset': 'AI Offset',
        'diOffset': 'DI Offset',
        'piOffset': 'PI Offset',
        'aoOffset': 'AO Offset',
        'poOffset': 'PO Offset',
        'noEmpty': 'Cannot be empty',
        'deviceImportSuccess': 'Device imported',
        'normalSet': 'The current set must be a natural number',
        'realSet': 'The current set must be a real number',
        'setFormat': 'Set should be a number anmd cannot be empty',
        'deviceName': 'Device Name',
        'model': 'Model',
        'operation': 'Operation',
        'dataView': 'View Data',
        'deviceDeleteTip': 'Are you sure you want to delete the device?',
        'batchDeviceDeleteTip': 'Are you sure you want to delete the selected device?',
        'pointName': 'Point',
        'relateDevice': 'Device Name',
        'description': 'Description',
        'finalValue': 'Final Value',
        'rate': 'Coefficient',
        'baseValue': 'Base Value',
        'quality': 'Quality',
        'time': 'Time stamp',
        'setNum': 'Set',
        'send': 'Send',
        'addSet': 'Set',
        'editOnline': 'Edit Online',
        'onlyCsv': 'Supports only .csv',
        'fileEmpty': 'The file cannot be empty',
        'fileFieldError': 'The file contains invalid fields',
        'templateNameEmpty': 'The name of the template cannot be empty',
        'versionEmpty': 'Version cannot be empty',
        'assetIdEmpty': 'Asset Id cannot be empty',
        'offsetWrong': 'Invalid offset format',
        'importDevice': 'Import Device',
        'selectFile': 'Select file',
        'file': 'File',
        'multiChannel': 'Multi-channel',
        'searchHint': 'Search by keyword',
        'testTip': 'The value takes effect after you publish the connection.',
        'deviceImport': 'Asset ID of the failed device: {0}',
        'localRepeatOther': 'The local address is a duplicate of the address of another connection',
        'serverRepeatOtherLocal': 'The remote address is a duplicate of the local address of another connection',
        'localRepeatOtherServer': 'The local address is a duplicate of the remote address of another connection',
        'ipEmpty': 'IP address cannot be empty',
        'serverLocalRepeat': 'Local address and remote address cannot be identical',
        'serverRepeat': 'Duplicate remote address',
        'primaryServerAddress': 'Remote Address(primary)',
        'secondaryServerAddress': 'Remote Address(Standby)',
        'primaryClientAddress': 'Local Address(primary)',
        'secondaryClientAddress': 'Local Address(Standby)',
        'remoteLabel': 'Remote:',
        'clientLabel': 'Local:',
        // access manage
        'ethernet': 'Ethernet',
        'serialPort': 'COM Port',
        'empty': 'None',
        'com': 'COM Port',
        'protocolLogTitle': 'protocol.sys Editing Log',
        'protocolLog': '{0} made change in {1}',
        'viewLog': 'View Editing Log',
        'downloadStandard': 'Download Standard .sys file',
        'serialNum': 'Serial Port',
        'commStatus': 'Comm Status',
        'edgeDetail': 'Edge Detail',
        'accessManage': 'Access Management',
        'deviceManage': 'Device Management',
        'assetTree': 'Asset Tree',
        'oddParity': 'Odd Parity',
        'evenParity': 'Even Parity',
        'noneParity': 'None',
        'serialPortNum': 'Serial Port',
        'serialEmpty': 'Serial Port cannot be empty',
        'baudRate': 'Baud Rate',
        'baudRateEmpty': 'Baud Rate cannot be empty',
        'dataBit': 'Data Bit',
        'dataBitEmpty': 'Data bit cannot be empty',
        'checkDigit': 'Check Bit',
        'checkDigitEmpty': 'Check Bit cannot be empty',
        'stopDigit': 'Stop Bit',
        'stopDigitEmpty': 'Stop bit cannot empty',
        'product': 'Product',
        'nodeType': 'Node Type',
        'gateway': 'Gateway',
        'device': 'Device',
        'view': 'View',
        'allProduct': 'All product',
        'deviceNum': 'Device Total: ',
        'deviceList': 'Device List'
    },
    'adddevice': {
        'num': 'Number',
        'deviceName': 'Device Name',
        'deviceModel': 'Model',
        'addNum': 'Add Count',
        'addDevice': 'Add Device',
        'selectProduct': 'Select product',
        'selectDevice': 'Select device',
        'selectTemplate': 'Select template',
        'enableMultichannel': 'Enable Multi-channel',
        'product': 'Product',
        'templateSet': 'Template Setting',
        'template': 'Template:',
        'templateType': 'Device Model',
        'version': 'Version',
        'protocol': 'Protocol',
        'driver': 'Driver',
        'searchhint': 'Search by keyword'
    },
    'template': {
        'templateImportSuccess': 'Template Imported',
        'templateRepeat': 'Template of the same name and version already exists',
        'fieldMiss': 'The following fields are missing or empty：',
        'modelNoExist': 'Model does not exist',
        'protocolNoExist': 'Protocol does not exist',
        'templateName': 'Template Name',
        'version': 'Version',
        'model': 'Model',
        'protocol': 'Protocol',
        'associateEdge': 'Associate Edge',
        'deviceModel': 'Device Type',
        'creator': 'Creator',
        'updateTime': 'Last Updated',
        'operation': 'Operations',
        'copy': 'Copy',
        'deleteTitle': 'Delete Template',
        'noDeleteTip': 'The template is used by device and cannot be deleted',
        'deleteTip': 'Are you sure you want to delete template?',
        'template': 'Template',
        'searchHint': 'Search by keyword',
        'copyTitle': 'Copy Template',
        'templateEmpty': 'Template name cannot be empty',
        'device': 'Device',
        'associateTitle': 'Connected Device',
        'addTemplate': 'Add Template',
        'brand': 'Brand',
        'brandEmpty': 'Brand required',
        'deviceModelEmpty': 'Device type required',
        'versionEmpty': 'Version required',
        'modelEmpty': 'Model required',
        'modelSelect': 'Select Model',
        'fileEmpty': 'File or file data cannot be empty',
        'fileFieldError': 'Fields of file cannot be empty',
        'saveConfirm': 'This operation may lead to losing existing mappings, ' +
        'Check the mappings before performing this operation.',
        'featureType': 'Feature Type',
        'name': 'Name',
        'identifier': 'Identifier',
        'dataType': 'Data Type',
        'uploadType': 'Upload Type',
        'uploadInterval': 'Upload Interval',
        'mapping': 'Mapping',
        'mappingTip': 'Mapping Points',
        'templateEdit': 'Edit Template',
        'basicInfo': 'Basic Information',
        'pointMap': 'Points Mapping',
        'editPointFile': 'Edit Point File',
        'pointFileEmpty': 'Point file cannot be empty',
        'fileUploadSuccess': 'File uploaded',
        'protocolType': 'Protocol Type',
        'protocolTypeEmpty': 'Select protocol type',
        'protocolEmpty': 'Select protocol',
        'pointFile': 'Point File',
        'templateDownload': 'Download Template',
        'noPointFile': 'Upload point.csv file',
        'onlyCsv': 'Supports only .csv',
        'pointName': 'Point Name',
        'type': 'Type',
        'description': 'Description',
        'alias': 'Alias',
        'selectCollectPoint': 'Select collecting point',
        'collect': 'Collect',
        'control': 'Control',
        'formula': 'Formula',
        'availableCollect': 'Optional Collecting Points',
        'operandSet': 'Operand Set',
        'chosenCollect': 'Chosen Points',
        'addFormula': 'Add Formula',
        'clearMapping': 'Clear Mapping',
        'operand': 'Operands',
        'operandReg': 'Operand must be number',
        'changeProtoTypeTitle': 'Change Protocol Type',
        'changeProtocolTitle': 'Change Protocol',
        // eslint-disable-next-line max-len
        'changeProtoTypeTip': 'Changing the protocol type will change the selected protocol. Are you sure you want to modify the protocol type?',
        // eslint-disable-next-line max-len
        'changeProtocolTip': 'Changing the protocol will result in the loss of domain points mapping. Are you sure you want to modify the protocol?',
        'selectProtocolTip': 'Select protocol',
        'relateConfirmTitle': 'Confirm editing',
        // eslint-disable-next-line max-len
        'relateConfirmContent': 'This template has been associated with {0} Edge gateway. Select the Edge gateway to update the template',
        'view': 'View',
        'jsonError': 'Invalid JSON format. Check your file',
        'jsonOnly': 'Supports only JSON file',
        'noSelect': 'This will create a new template. Enter the name of the new template:',
        // eslint-disable-next-line max-len
        'someSelect': 'This will create a new template for the selected Edge. Enter the name of the new template:',
        'publicModel': 'Public Model',
        'privateModel': 'Private Model',
        'templateNameFormat': 'Template name can only contain Chinese, numbers, letters and "-", "_", ".", and ":"',
        'innerVersionFormat': 'InnerVersion can only contain numbers, letters, period (.) and underscore (_)',
        'intervalFormat': 'Upload Interval can only be an integer greater than 0',
        'noMappingTip': 'This type of point does not support mapping',
        'protocolDetail': 'Protocol Detail',
        'script': 'Script',
        'scriptName': 'Script Name',
        'scriptContent': 'Script Content',
        'addScript': 'Create Script',
        'editScript': 'Edit Script',
        // eslint-disable-next-line max-len
        'scriptValidName': 'The script name can only contain letters, numbers, hyphen, and underscore. It cannot be empty',
        'scriptContentEmpty': 'Script content cannot be empty',
        'scriptImportSuccess': 'Script imported',
        'scriptJsonWrong': 'Invalid file format',
        'scriptImportEmpty': 'The file cannot be empty',
        'titleMiss': 'Script name or script content field is missing',
        'scriptNameRepeat': 'Script name already exists',
        // eslint-disable-next-line max-len
        'importScriptName': 'Script name can only contain letters, numbers, hyphen and underscores. It cannot be empty',
        'importScriptContent': 'Script content cannot be empty and should be string',
        'scriptInfoListWrong': 'scriptInfoList can only be array',
        'scriptContentWrong': 'The content of scriptInfoList array should be object',
        // eslint-disable-next-line max-len
        'disProtocolTip': 'The template has been associated with the device and the protocol type cannot be changed',
        'importArray': 'The content of the imported file should be array',
        'bigEqualZero': 'Positive numbers and 0 supported.'
    },
    'protocol': {
        'deleteTitle': 'Confirm Delete',
        'deleteProtocol': 'Are you sure you want to delete the protocol?',
        'protocolName': 'Protocol Name',
        'protocolType': 'Protocol Type',
        'description': 'Description',
        'associateEdge': 'Associated Edge',
        'creator': 'Creator',
        'createTime': 'Created On',
        'operation': 'Operations',
        'relateCollectNoDelete': 'Cannot delete the protocol because it has associated connections.',
        'protocolTitle': 'Protocol',
        'addProtocol': 'Add',
        'addProtocolTitle': 'Add Protocol',
        'searchHint': 'Search by keyword',
        'versionDesc': 'Version Description',
        'bin': 'Package',
        'template': 'Template',
        'collect': 'Connection',
        'associateInfo': 'Associate Information',
        'editProtocol': 'Edit Protocol',
        'binEmpty': 'Package cannot be empty',
        'binTip': 'Package can only select bin file',
        'configTemp': 'System Configuration',
        'configTempEmpty': 'System Configuration cannot be empty',
        'sysType': 'System Configuration supports only .sys file',
        'pointTemp': 'Point',
        'pointTempEmpty': 'Point cannot be empty',
        'pointType': 'Point supports only .csv',
        'desc': 'Description',
        'descEmpty': 'Description cannot be empty',
        'protocolDesc': 'Description',
        'protocolDoc': 'Document',
        'upgradeProtocol': 'Upgrade Protocol',
        'upgradeReason': 'Upgrade Reason',
        'upgradeReasonEmpty': 'Upgrade reason cannot be empty',
        'newFeature': 'New Feature',
        'bugFix': 'Bug Fix',
        'affect': 'Impact Scope',
        'onlyBin': 'Supports only .bin file',
        'onlySys': 'Supports only .sys file',
        'onlyCsv': 'Supports only .csv file',
        'selectProtocolType': 'Select protocol type',
        'role': 'Role',
        'roleEmpty': 'Role cannot be empty',
        'name': 'Name',
        'nameEmpty': 'Name cannot be empty',
        'nameRule': 'Supports only numbers, letters, hyphen (-), or underscore (_) ',
        'releaseConfirm': 'Are you sure you want to release the protocol?',
        'releaseSuccess': 'Protocol released',
        // eslint-disable-next-line max-len
        'saveTip': 'This action will affect all templates associated with the protocol and the devices that use them. Confirm the impact of the operation before saving.',
        'clickToChoose': 'Click to select',
        'chooseAffectCollect': 'Select Affected Connections'
    },
    'collecttest': {
        'setNumSuccess': 'Set sent',
        'paramEmpty': 'Parameter cannot be empty',
        'alert': 'Data value set takes effect after the connection is published.',
        'status': 'Connection State',
        'normal': 'Normal',
        'abnormal': 'Abnormal',
        'ip': 'IP Address',
        'deviceCount': 'Sub-devices',
        'data': 'Data',
        'message': 'Message',
        'log': 'Log',
        'clear': 'Clear',
        'begin': 'Start',
        'pause': 'Pause',
        'pingHint': 'Enter IP address, e.g. 192.168.10.10',
        'telnetHint': 'Enter IP address and port, e.g. 192.168.10.10 12000',
        'tcpHint': 'Enter port, e.g. 12000',
        'execute': 'Execute',
        'ifconfig': 'Local IP',
        'ping': 'Ping',
        'telnet': 'Telnet',
        'netstat': 'TCP Connections',
        'numHint': 'Set should be a number and cannot be empty',
        'point': 'Point',
        'deviceName': 'Device Name',
        'description': 'Description',
        'final': 'Value',
        'rate': 'Coefficient',
        'base': 'Offset',
        'quality': 'Quality',
        'timestamp': 'Time Stamp',
        'set': 'Set',
        'send': 'Send',
        'cancel': 'Cancel',
        'addSet': 'Add Set',
        'console': 'Console',
        'ethernet': 'Ethernet',
        'test': 'Test Connection',
        'search': 'Search by keyword',
        'serialPort': 'Serial Port'
    },
    'devicelist': {
        'number': 'Number',
        'name': 'Device Name',
        'type': 'Device Type',
        'model': 'Device Model',
        'box': 'Box',
        'status': 'Connection State',
        'trsconf': 'Communication Configuration',
        'operation': 'Operations',
        'normal': 'Normal',
        'disconnect': 'Disconnect',
        'unconf': 'Unconfigured',
        'conf': 'Configured',
        'click2conf': 'Configure',
        'detail': 'Detail',
        'release': 'Release Configuration',
        'confirm': 'Confirm Release',
        'releasehint': ' The operation will remove the device from the corresponding box. Are you sure you want to continue?',
        'releasecontine': 'Continue to Release',
        'searchhint': 'Search devices',
        'unplugin': 'Unplug',
        'conn': 'Connection'
    }, 
    'devicetpllist': {
        'schemaNotExist': 'Mapping name does not exist',
        'jsonError': 'Invalid JSON format. Check your file',
        'modelNotExist': 'The deviceModelName does not exist and cannot be imported',
        'protocolNotExist': 'The protocolName does not exist and cannot be imported',
        'modelDup': 'model and innerVer are duplicate. The model and innerVer already exist',
        'deviceNameDup': 'Device name already exists',
        'fieldMissing': 'Missing',
        'jsonType': 'Upload JSON file',
        'importTemplate': 'Import',
        'addDuplicate': 'Failed to add due to duplicate model and version',
        'add': 'New Template',
        'delete': 'Delete',
        'update': 'Update',
        'detail': 'Detail',
        'copy': 'Copy',
        'name': 'Name',
        'type': 'Model',
        'asssites': 'Associated Sites',
        'assdriver': 'Protocol',
        'editor': 'Editor',
        'operation': 'Operations',
        'newtpl': 'Create Template',
        'tplname': 'Template Name',
        'nodup': 'No Duplication',
        'selectdomain': 'Select Domain',
        'creator': 'Creator',
        'updateTime': 'Last Modified',
        'isConfirmDelete': 'Deleting this model set ' +
        'may have an impact on historical data generation. Do you want to continue?',
        'brand': 'Brand',
        'model': 'Product Model',
        'version': 'Version',
        'station': 'Site',
        'associatedDevice': 'Device on Site',
        'there': 'There are',
        'aS': 'Associated Site',
        'hint': 'Note:Only the list of sites under ownership of this account is displayed',
        'searchhint': 'Search templates',
        'relatedDevice': 'The template has associated devices and cannot be deleted'
    },
    'ASSET': {
        LABEL_NODE: 'Node',
        LABEL_MODEL: 'Model',
        LABEL_CHOOSE_PRODUCT: 'Select Product',
        LABEL_CHOOSE_DEVICE: 'Select Device',

        LABEL_NO_NODE_HINT: 'Click "+" to create asset tree',
        REF_HINT: 'Ensure that the node does not have child nodes before deleting the node. Deleting a node does not affect the asset instance bound to the node.',
        REF_HINT2: 'Are you sure you want to remove the node: {0} ?',
        // eslint-disable-next-line max-len
        INS_HINT: 'Deleting an asset instance removes all nodes that this instance is bound to from the asset tree. Ensure that all binding nodes of this asset instance do not have child nodes.',
        INS_HINT2: 'Are you sure you want to delete the asset: {0} ?',
        INS_HINT3: 'Cannot delete the asset instance because one or multiple child nodes still exist. Delete all child nodes and try again.',

        NODE_INFO: 'Node Information',
        ABSTRACT: 'Basics',
        ASSET_TAG: 'Asset Tags',
        EDIT_ASSET_TAG: 'Edit Asset Tag',
        EDIT_ABSTRACT_INFO: 'Edit Basic Information',
        ASSET_NAME: 'Name',
        ASSET_NAME_EN: 'Name (English)',
        ASSET_NAME_HINT: 'Enter asset name',
        ASSET_NAME_EN_HINT: 'Enter asset name (English)',
        EDIT_SUCCESS: 'Change saved',
        BIND_SUCCESS: 'Device Bound',
        FALSE: 'No',
        TRUE: 'Yes',
        VIEW: 'View',
        SELECT: 'Bind',
        IS_BINDING: 'Is Connected Device',
        UPDATE_TIME: 'Last Modified',

        DELETE_FAIL: 'Cannot delete asset',
        NO_MATCH: 'No search result',
        DELETE_REF: 'Delete node',
        DELETE_INS: 'Delete asset',
        ADD_LEAF: 'Add leaf node',
        BASE_MODEL: 'Create asset from model',
        ADD_EXIST: 'Add existing asset',
        ADD: 'Add',
        SEARCH_FIELD: 'Search By',
        NAME: 'Name',
        KEYWORD: 'Keyword',
        CREATE_ROOT: 'Create Root Node',
        CREATE_ASSET: 'Create Asset from Model',
        BASE_INFO: 'Basic Information',
        PARENT_NODE: 'Parent Node',
        DEVICE_MODEL: 'Device Model',
        MODEL_SELECT_HINT: 'Select Model',
        IS_ACCESS: 'Is Connected Device',
        BIND_EXIST: '1.Bind device',
        QUICK_CREATE: '2.Create connected device',
        BIND_LATER: '3.Bind device later',
        FILL_LATER: 'Provide Later',
        ACCESS_DEVICE: 'Bind Device',
        PLEASE_SELECT: 'Select Device',
        ATTR: 'Attributes',
        SELECT_ACCESS: 'Select Connected Device',
        MODEL: 'Model',
        SELECT_PRODUCT: 'Select Product',
        SELECT_DEVICE: 'Select Device',
        ADD_EXIST_ASSET: 'Add Existing Asset',
        SELECT_MODEL: 'Select Model',
        SELECT_ASSET: 'Select Asset',
        LOAD_MORE: 'Load More',
        ASSET_TREE: 'Asset Tree',
        ADDBEFORE: 'Add Before',
        ADDAFTER: 'Add After',
        TREE_NAME: 'Name',
        TREE_NAME_EN: 'Name (English)',
        DELETE_INS_TITILE: 'Are you sure you want to delete instance',
        DELETE_INS_HINT: 'This is the last reference of the instance. Do you want to delete the instance?',
        NODE_ID: 'Node ID',
        INSTANCE_ID: 'Asset ID',
        TREE_ID: 'Tree ID',
        INPUT_DEVICE_NAME: 'Enter Name',
        TIMEZONE: 'Timezone/City',
        TIMEZONEACT: 'Use daylight saving time. Select the city.',
        TIMEZONESL: 'Select a timezone',
        ISDST: 'Use DST'
    }
};
